language: java
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
before_script:
  - sudo apt-get install astyle expect
  - mkdir src
  - mv common src/
  - mv dummy src/
  - mv resources src/
  - mv .gitignore src/
  - mv build.xml src/
  - mv expect.tcl src/
  - cd src
script: ant test
